### ISSUE TITLE
XLSX File have each cell warning: Number Stored as Text

### ISSUE THREAD

**Issue by cricrazy** [mentax/csv2xlsx#1]
The CSV2XLSX converter works great and fast. But when I opened Excel. All the number cells has a warning (green triangle or top left corner), that 

**Number Stored as Text.**

How do you fix this. 

![csvxlsx](https://user-images.githubusercontent.com/4622816/36810550-a1321bd4-1c90-11e8-8bb8-91ae0aaa17fc.png)

**Comment by DeyV** [comment]
v0.3 should fix this problem
