### ISSUE TITLE
Running out of memory even though the compute node has available memory

### ISSUE THREAD

**Issue by AyushSaxena** [mentax/csv2xlsx#10]
Here is the command I'm trying to run - 

csv2xlsx -colsep "," -columns "0:text,1:number,2:percent" -headerlines 1 --infile input.csv  --outfile output.xlsx --overwrite
The csv is 76M large

And here is the error I'm receiving. I have run this on 16G and then 64G memory nodes.

Converting input.csv => output.xlsx

runtime: out of memory: cannot allocate 536870912-byte block (3333586944 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x8274187, 0xd)
        /usr/local/opt/go/libexec/src/runtime/panic.go:1116 +0x6a
runtime.largeAlloc(0x1ffff000, 0x8090101, 0xd0a62150)
        /usr/local/opt/go/libexec/src/runtime/malloc.go:1154 +0x103
runtime.mallocgc.func1()
        /usr/local/opt/go/libexec/src/runtime/malloc.go:1047 +0x39
runtime.systemstack(0xa7020e0)
        /usr/local/opt/go/libexec/src/runtime/asm_386.s:395 +0x53
runtime.mstart()
        /usr/local/opt/go/libexec/src/runtime/proc.go:1041

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/opt/go/libexec/src/runtime/asm_386.s:356 fp=0xa8a7154 sp=0xa8a7150 pc=0x80a01e0
runtime.mallocgc(0x1ffff000, 0x82380a0, 0x804b101, 0x826cca0)
        /usr/local/opt/go/libexec/src/runtime/malloc.go:1046 +0x6aa fp=0xa8a71a8 sp=0xa8a7154 pc=0x805288a
runtime.makeslice(0x82380a0, 0x1ffff000, 0x1ffff000, 0x30)
        /usr/local/opt/go/libexec/src/runtime/slice.go:49 +0x4f fp=0xa8a71bc sp=0xa8a71a8 pc=0x808beaf
bytes.makeSlice(0x1ffff000, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/bytes/buffer.go:229 +0x64 fp=0xa8a71d8 sp=0xa8a71bc pc=0x80b2a54
bytes.(*Buffer).grow(0xa0980e0, 0x1000, 0x8249440)
        /usr/local/opt/go/libexec/src/bytes/buffer.go:142 +0x11c fp=0xa8a7200 sp=0xa8a71d8 pc=0x80b24ac
bytes.(*Buffer).Write(0xa0980e0, 0xa120000, 0x1000, 0x1000, 0x4, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/bytes/buffer.go:172 +0xb5 fp=0xa8a7214 sp=0xa8a7200 pc=0x80b2715
bufio.(*Writer).Flush(0xa0981a0, 0x78232d30, 0x5)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:591 +0x5d fp=0xa8a7248 sp=0xa8a7214 pc=0x80b6a7d
bufio.(*Writer).WriteString(0xa0981a0, 0x78232d30, 0x8, 0x1, 0xa8a721c, 0x80b7199)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:694 +0x35 fp=0xa8a7268 sp=0xa8a7248 pc=0x80b70a5
encoding/xml.(*printer).EscapeString(0x57e7e000, 0x78232d30, 0x8)
        /usr/local/opt/go/libexec/src/encoding/xml/xml.go:1982 +0x29a fp=0xa8a72a0 sp=0xa8a7268 pc=0x816ad3a
encoding/xml.(*printer).writeStart(0x57e7e000, 0xa8a73a4, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:717 +0x223 fp=0xa8a7310 sp=0xa8a72a0 pc=0x815b593
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x825e4e0, 0x782381a0, 0x199, 0xadddc344, 0x0, 0x199, 0x808c112)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:519 +0x5b6 fp=0xa8a73e0 sp=0xa8a7310 pc=0x8159306
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x82263e0, 0x9dc67040, 0x197, 0xadddc344, 0x0, 0x197, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:455 +0x29d fp=0xa8a74b0 sp=0xa8a73e0 pc=0x8158fed
encoding/xml.(*printer).marshalStruct(0x57e7e000, 0x57e4df20, 0x825e620, 0x9dc67030, 0x199, 0x9dc67055, 0x188)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:941 +0x1f5 fp=0xa8a7550 sp=0xa8a74b0 pc=0x815c655
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x825e620, 0x9dc67030, 0x199, 0x57e77380, 0x0, 0x199, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:524 +0x602 fp=0xa8a7620 sp=0xa8a7550 pc=0x8159352
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x8226860, 0x57e8005c, 0x197, 0x57e77380, 0x0, 0x197, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:455 +0x29d fp=0xa8a76f0 sp=0xa8a7620 pc=0x8158fed
encoding/xml.(*printer).marshalStruct(0x57e7e000, 0x57e4df00, 0x824a160, 0x57e8004c, 0x199, 0x16, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:941 +0x1f5 fp=0xa8a7790 sp=0xa8a76f0 pc=0x815c655
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x824a160, 0x57e8004c, 0x199, 0xaddde0dc, 0x0, 0x199, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:524 +0x602 fp=0xa8a7860 sp=0xa8a7790 pc=0x8159352
encoding/xml.(*printer).marshalStruct(0x57e7e000, 0x55543f20, 0x8266860, 0x57e80000, 0x199, 0x16, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:941 +0x1f5 fp=0xa8a7900 sp=0xa8a7860 pc=0x815c655
encoding/xml.(*printer).marshalValue(0x57e7e000, 0x823eae0, 0x57e80000, 0x16, 0x0, 0x0, 0x50, 0x8243ae0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:524 +0x602 fp=0xa8a79d0 sp=0xa8a7900 pc=0x8159352
encoding/xml.(*Encoder).Encode(0x57e7e000, 0x823eae0, 0x57e80000, 0xa120000, 0x0)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:162 +0xa2 fp=0xa8a79fc sp=0xa8a79d0 pc=0x8157ae2
encoding/xml.Marshal(0x823eae0, 0x57e80000, 0xaddd6fac, 0x4, 0xa8a7d48, 0xaddd8000, 0x8)
        /usr/local/opt/go/libexec/src/encoding/xml/marshal.go:81 +0xee fp=0xa8a7a20 sp=0xa8a79fc pc=0x81578fe
github.com/tealeg/xlsx.(*File).MarshallParts.func1(...)
        /Users/armin/sourcecode/golang/src/github.com/tealeg/xlsx/file.go:279
github.com/tealeg/xlsx.(*File).MarshallParts(0xa02c080, 0xe7bb0f10, 0x809d4b0, 0xa0b8e40)
        /Users/armin/sourcecode/golang/src/github.com/tealeg/xlsx/file.go:324 +0x61b fp=0xa8a7e1c sp=0xa8a7a20 pc=0x81e178b
github.com/tealeg/xlsx.(*File).Write(0xa02c080, 0x82c5d80, 0x57e5fd18, 0x1b6, 0x57e5fd18)
        /Users/armin/sourcecode/golang/src/github.com/tealeg/xlsx/file.go:139 +0x2f fp=0xa8a7eb0 sp=0xa8a7e1c pc=0x81e05ef
github.com/tealeg/xlsx.(*File).Save(0xa02c080, 0xffadd97b, 0x31, 0x3, 0x3)
        /Users/armin/sourcecode/golang/src/github.com/tealeg/xlsx/file.go:130 +0x6b fp=0xa8a7ed4 sp=0xa8a7eb0 pc=0x81e055b
main.convertFile(0xffadd940, 0x30, 0xffadd97b, 0x31, 0x4)
        /Users/armin/sourcecode/golang/src/arminhanisch.de/csv2xlsx/csv2xlsx.go:554 +0x2db fp=0xa8a7f48 sp=0xa8a7ed4 pc=0x8207b5b
main.main()
        /Users/armin/sourcecode/golang/src/arminhanisch.de/csv2xlsx/csv2xlsx.go:584 +0xd1 fp=0xa8a7fc8 sp=0xa8a7f48 pc=0x8207fb1
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:203 +0x1fd fp=0xa8a7ff0 sp=0xa8a7fc8 pc=0x807979d
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_386.s:1337 +0x1 fp=0xa8a7ff4 sp=0xa8a7ff0 pc=0x80a1a11
        
Thank you,
Ayush

**Comment by DeyV** [comment]
tell me the version you are using and what operating system?

**Comment by DeyV** [comment]
but, as I see, You try use not exisitgs in  **csv2xlsx**  params: -columns, -headerlines
check example in file: https://github.com/mentax/csv2xlsx/blob/master/example/big/run.sh
