### ISSUE TITLE
I have added some features

### ISSUE THREAD

**Issue by kshji** [mentax/csv2xlsx#2]
I added some extensions for your excellent packet.

[https://github.com/kshji/go/tree/master/csv2xlsx](https://github.com/kshji/go/tree/master/csv2xlsx)

If you take those extensions to your code, then I'll remove my version. I have no need to offer other versions.

- csv headerlines handling, headerline writing
- template Format support added
- CSV column separator option
- Excel formula support in template and in csv, csv formula overwrite template formulas
- debug option
- verbose option, show rownumber  - processin g ....
- startrow option, which csv line is first to read
- more command line options, I use global param struct, not so nice, someone could fix nicer. I'm so Go beginner ...
- also footer template ex. including sum column
- environment variable extension

**Comment by DeyV** [comment]
if you like - create merge request.

**Comment by kakadais** [comment]
Please merge this.

**Comment by DeyV** [comment]
i'm waiting for merge request

**Comment by kakadais** [comment]
@DeyV Do you have an idea for the number to string formatting? 
A small number is okay but a long number such as '1114012700100530002020472' is formatting as exponential numbers.
I just want to change all fields to string with any data.

**Comment by DeyV** [comment]
Probably You can type an apostrophe (') in front of the number, and Excel will treat it as text.

**Comment by kakadais** [comment]
@DeyV Single '? I tried annoying =""  surrounding but ' would be easy to handle if it works. I'll try-

**Comment by DeyV** [comment]
full support for ' in 0.4 release
