### ISSUE TITLE
new option for a column wrapper

### ISSUE THREAD

**Issue by jabraga** [mentax/csv2xlsx#7]
could you add a option to specify the individual column wrapper.  something like -colwrap ":" or even -colwrap "" to ingore.   We have an issue with the conversion now where if double quotes are contained in the data but that do not completely wrap the data then the row does not properly parse with the -colsep option.

Also, I noticed that number fields when coverted get an exclamation point as to say they should be number but the are actually not being treated that way.

**Comment by DeyV** [comment]
Can you show example file / template that show this problem?

**Comment by DeyV** [comment]
I'm closing. No response for long time
