### ISSUE TITLE
latest OSX won't let me run this

### ISSUE THREAD

**Issue by fredzannarbor** [mentax/csv2xlsx#8]
Hi,

Trying to download the release & run but having problems presumably b/c of OS X security. I am running OS X 12.6.  I would expect that when I click the app for the first time I would see the warning message appear on the Security & Privacy > General page that gives me the option to allow this particular program to run.  It is not there.

**Comment by DeyV** [comment]
please, try version 0.4.2
On my M1 and MacOs Ventura (13 beta) binary [csv2xlsx_0.4.2_MacOS_all.tar.gz](https://github.com/mentax/csv2xlsx/releases/download/v0.4.2/csv2xlsx_0.4.2_MacOS_all.tar.gz) 
correctly show security alert and warning message appear on the Security & Privacy tab
