### ISSUE TITLE
Repaired Records: Cell information from /xl/worksheets/sheet1.xml part

### ISSUE THREAD

**Issue by nyilasviktor0625** [mentax/csv2xlsx#9]
Hello I really need your help.
I export data from oracle database to csv file and then convert it to xlsx format then it gives the following error
Please help me,
Thank you,
Viktor
![image](https://user-images.githubusercontent.com/55741832/205887292-214eaecb-c1c8-4ba0-8d79-06ca9b092dc3.png)
![image](https://user-images.githubusercontent.com/55741832/205887380-9b8ddbe3-fa23-4e07-bf09-5c256341f7cb.png)

**Comment by nyilasviktor0625** [comment]
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

**Comment by nyilasviktor0625** [comment]
![image](https://user-images.githubusercontent.com/55741832/205951239-e7cc2013-48d1-4f5b-8dee-e8cec16b24be.png)

**Comment by DeyV** [comment]
Can You attach example file
And command executed by you

**Comment by 8bitjoe** [comment]
I'm having the same issue, files created opens in libreoffice but not in microsoft excel, any ideas? Excel complains about corruption, attempts to recover the file then shows an empty file.

**Comment by DeyV** [comment]
Please attach the simplest file with template and data to reproduce the problem

**Comment by ufoonline** [comment]
Hello,

I've the same issue of the user, attached you can find the output of:
./csv2xlsx --template csv2xlsx.git/example/template.xlsx -s Sh1 -r 4 csv2xlsx.git/example/big/data.csv

The binary file used is: v0.4.4/csv2xlsx_Linux_x86_64.tar.gz

Regards
[output.xlsx](https://github.com/mentax/csv2xlsx/files/12880307/output.xlsx)

**Comment by DeyV** [comment]
@ufoonline  can you attach example template.xlsx and data.csv, that generate this error ?

**Comment by ufoonline** [comment]
@DeyV Here they are.

They are the same files present in the repository.

[data.csv](https://github.com/mentax/csv2xlsx/files/13250942/data.csv)
[template.xlsx](https://github.com/mentax/csv2xlsx/files/13250944/template.xlsx)

Best Regards

**Comment by DeyV** [comment]
Thank you for this additional information @ufoonline  

I confirm - Linux version 0.4.4 also generates this error for me

However, version 0.5.0 now works properly. I encourage you to check it out
